### PR TITLE
v1.1.2 (v1.2.0 >= won't be archived) 

### PR DESCRIPTION
**Pull request by byanko55**
**Bug Fixes**
* Dependency issue from jekyll < 4.0
* Overlapped nav contents
* Category name is not shown properly

### CODE REVIEW

**Comment by cvlian** [comment]
The rollback may cause serious impacts for the later versions. Very unwelcome situation though, you were lucky to remove the problematic versions.

I found that uploading same version twice is blocked. It means, the next version tag should begin with `1.2.5` (since v1.2.0~1.2.4 are yanked).

image


We must reorganize the build test processes to prevent this mess from happening again.

**Comment by byanko55** [comment]
I truly agree with that we should not have been to hasty.

Here is my checklist for the basic features:

|Features|Build by git fork|Build by gem package|
|---|---|---|
|Theme change|○|○|
|Search|○|○|
|Nav|○|○|
|Pagination|○|○|
|Visitor counter|○|○|
|Giscus|○|○|
|Categorization|○|○|
|Tag|○|○|
|Toc|○|○|
|Top button|○|○|
|Related Posts|○|○|

Anything I have missed?

**Comment by mgarrixx** [comment]
I still get a failure.

```
/usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-satellite theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:4[39](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7778933142/job/21209315221#step:4:40):in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:[42](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7778933142/job/21209315221#step:4:43):in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'jekyll-theme-satellite' (>= 0) among 151 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
	from /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:986:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:[43](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7778933142/job/21209315221#step:4:44)9:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:[55](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7778933142/job/21209315221#step:4:56):in `config='
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:[70](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7778933142/job/21209315221#step:4:71):in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml Theme: jekyll-theme-satellite github-pages 228 | Error: The jekyll-theme-satellite theme could not be found.
```

**Comment by byanko55** [comment]
@mgarrixx  

Try this:

```
# in _config.yml

remote_theme: byanko55/jekyll-theme-satellite # theme: jekyll-theme-satellite
```

**Comment by mgarrixx** [comment]
I found inserting below lines makes build process complete.

```
plugins:
  - jekyll-theme-satellite
```

But, the problem is: **it is NOT the layout we have developed.**

image

**Comment by byanko55** [comment]
So, here are the cases:

* Build Git page by Fork/Source.zip -> OK
* Build locally by Fork/Source.zip -> OK
* **Build Git page based on Gem package -> NOPE**
* Build locally based on Gem package -> OK

Only the option that deploys the site on Git page with Gem package caused trouble, didn't it?

**Comment by mgarrixx** [comment]
> @mgarrixx
> 
> Try this:
> 
> ```
> # in _config.yml
> 
> remote_theme: byanko55/jekyll-theme-satellite # theme: jekyll-theme-satellite
> ```

That gives me another error log!  ( ┛△┗ )

```
Liquid Exception: Liquid syntax error (/tmp/jekyll-remote-theme-20240205-8-1jz4xe6/_includes/sidebar.html line 2): Expected end_of_string but found id included in /_layouts/page.html
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/parser.rb:[16](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:17):in `consume': Liquid syntax error (/tmp/jekyll-remote-theme-20240205-8-1jz4xe6/_includes/sidebar.html line 2): Expected end_of_string but found id included  (Liquid::SyntaxError)
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/filters.rb:369:in `parse_condition'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/filters.rb:200:in `where_exp'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/strainer.rb:56:in `invoke'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:86:in `invoke'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:84:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `each'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `inject'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/assign.rb:26:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:2[18](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:19):in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/tags/include.rb:140:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/tags/include.rb:137:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/tags/include.rb:140:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/tags/include.rb:137:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:126:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:[19](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:20)5:in `render_layout'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:88:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:463:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:463:in `block in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:462:in `each_value'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:462:in `render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:191:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:2[20](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:21):in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:[22](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:23)0:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:[23](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:24):in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings Requiring: jekyll-remote-theme GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Theme: byanko55/jekyll-theme-satellite Theme source: /tmp/jekyll-remote-theme-20[24](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:25)0205-8-1jz4xe6 Remote Theme: Using theme byanko55/jekyll-theme-satellite Remote Theme: Downloading https://codeload.github.com/byanko55/jekyll-theme-satellite/zip/HEAD to /tmp/jekyll-remote-theme-20240205-8-qgfgay.zip Remote Theme: Unzipping /tmp/jekyll-remote-theme-20240205-8-qgfgay.zip to /tmp/jekyll-remote-theme-20240205-8-1jz4xe6 Requiring: jekyll-feed Requiring: jekyll-sitemap Requiring: jekyll-seo-tag Reading: _pages/Category B/Subcategory b/Subsubcategory 2/post-05.md Reading: _pages/Category B/Subcategory b/Subsubcategory 2/index.md Reading: _pages/Category B/Subcategory b/post-03.md Reading: _pages/Category B/Subcategory b/index.md Reading: _pages/Category B/Subcategory b/Subsubcategory 1/post-04.md Reading: _pages/Category B/Subcategory b/Subsubcategory 1/index.md Reading: _pages/Category B/Subcategory c/index.md Reading: _pages/Category B/index.md Reading: _pages/posting guide.md Reading: _pages/markdown guide.md Reading: _pages/visitor counter.md Reading: _pages/comment system.md Reading: _pages/Category A/Subcategory a/post-02.md Reading: _pages/Category A/Subcategory a/post-01.md Reading: _pages/Category A/Subcategory a/index.md Reading: _pages/Category A/index.md Reading: _pages/index.md Generating: JekyllOptionalFrontMatter::Generator finished in 5.5324e-05 seconds. Generating: JekyllReadmeIndex::Generator finished in 5.7949e-05 seconds. Generating: Jekyll::Paginate::Pagination finished in 5.861e-06 seconds. Generating: JekyllRelativeLinks::Generator finished in 1.9907e-05 seconds. Generating: JekyllDefaultLayout::Generator finished in 1.3976e-05 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 1.3365e-05 seconds. Rendering: _pages/Category A/Subcategory a/index.md Pre-Render Hooks: _pages/Category A/Subcategory a/index.md Rendering Markup: _pages/Category A/Subcategory a/index.md Requiring: kramdown-parser-gfm Rendering Layout: _pages/Category A/Subcategory a/index.md Layout source: theme Rendering: _pages/Category A/Subcategory a/index.md/#excerpt Pre-Render Hooks: _pages/Category A/Subcategory a/index.md/#excerpt Rendering Markup: _pages/Category A/Subcategory a/index.md/#excerpt GitHub Metadata: Generating for mgarrixx/mgarrixx.github.io GitHub Metadata: Calling @client.pages("mgarrixx/mgarrixx.github.io", {}) github-pages 2[28](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:29) | Error: Liquid syntax error (/tmp/jekyll-remote-theme-202[40](https://github.com/mgarrixx/mgarrixx.github.io/actions/runs/7779812400/job/21211550987#step:4:41)205-8-1jz4xe6/_includes/sidebar.html line 2): Expected end_of_string but found id included Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20240205-8-1jz4xe6
```

**Comment by byanko55** [comment]
That exception is what I fixed in this patch (See [06c36b4](https://github.com/byanko55/jekyll-theme-satellite/pull/32/commits/06c36b42d307d6b23837407c0f19cf9ee19341e2)).

After I close this PR, could you try it once again?

Don't try it so hard. My opinion is, nothing could be better options than 'fork' for Git page.

**Review by mgarrixx — APPROVED** [review]
Anyway... as long as both options can be carried out in their own way.

**Comment by cvlian** [comment]
> Anyway... as long as both options can be carried out in their own way.

I found a post about 'remote_theme' in Jekyll Forum. Give it a try.

https://talk.jekyllrb.com/t/help-installing-jekyll-theme-on-github-pages/5164

**Review by cvlian — APPROVED** [review]
> I truly agree with that we should not have been to hasty.
>
> Here is my checklist for the basic features:
>
> Anything I have missed?

That's good enough, Thanks.

**Pull request merged**
