### PR TITLE
v1.2.4 (1.2.0~1.2.3 were deprecated)

### PR DESCRIPTION
**Pull request by byanko55**
**New Features**
* Remove Jquery dependency
* Improve site performance
* Lazy image-loading plugin

**Minor Updates**
* Compress/Combine css/js resources
* Change loading gif image
* Use lightweight font/image resources
* Home title hover effect

**Bug Fixes**
* Unwanted indent from 2nd~3rd lines of related posts
* Vertical margin of tag items is not set
* Browser tab shows page title as `Index`

### CODE REVIEW

**Review by mgarrixx — COMMENTED** [review]
From firefox, code highlighter does not work

**Comment by byanko55** [comment]
> From firefox, code highlighter does not work

In Windows 11, it's normal. Could it be also dependent on OS?

**Comment by cvlian** [comment]
> > From firefox, code highlighter does not work
> 
> In Windows 11, it's normal. Could it be also dependent on OS?

Works prettry well on FireFox 120/MacOS (Ventura), What enviornment have you tested on? @mgarrixx

**Comment by mgarrixx** [comment]
Updating the latest version solves the issue.

**Review by mgarrixx — APPROVED** [review]

**Review by cvlian — APPROVED** [review]
All tests were completely passed. We'll wrap it up.

**Pull request merged**
