### PR TITLE
v1.4.0

### PR DESCRIPTION
**Pull request by byanko55**
**New Features**
* Allow to deploy the blog on a sub URL (ex., `username.github.io/<somewhere else>/`)

**Bug Fixes**
* Remove useless console logs

### CODE REVIEW

**Comment by byanko55** [comment]
Here is a brief checklist:

|Features|Build by git fork|Build by gem package|Mobile View|Tablet View|
|---|---|---|---|---|
|Theme change|-|-|-|-|
|Search|-|-|-|-|
|Nav|-|-|-|-|
|Pagination|-|-|-|-|
|Visitor counter|-|-|-|-|
|Giscus|-|-|-|-|
|Categorization|-|-|-|-|
|Tag|-|-|-|-|
|Toc|-|-|-|-|
|Top button|-|-|-|-|
|Related Posts|-|-|-|-|
|Thumbnail|-|-|-|-|
|Clipboard|-|-|-|-|

Add more items if you have any.

**Comment by mgarrixx** [comment]
Bug#1: Theme button is not activating at root page (`'/'`), but it works in other URL paths.

**Comment by mgarrixx** [comment]
> Bug#1: Theme button is not activating at root page (`'/'`), but it works in other URL paths.

I got this error:

image

**Comment by mgarrixx** [comment]
I checked them all.

|Features|Build by git fork|Build by gem package|Mobile View|Tablet View|
|---|---|---|---|---|
|Theme change|O|-|O|O|
|Search|O|-|O|O|
|Nav|O|-|O|O|
|Pagination|O|-|O|O|
|Visitor counter|O|-|O|O|
|Giscus|O|-|O|O|
|Categorization|O|-|O|O|
|Tag|O|-|O|O|
|Toc|O|-|-|-|
|Top button|O|-|O|O|
|Related Posts|O|-|O|O|
|Thumbnail|O|-|O|O|
|Clipboard|O|-|O|O|

**Comment by cvlian** [comment]
Is there any way to check the goat-counter & giscus are working well?, It seems other requirements are fulfilled though.

**Comment by byanko55** [comment]
> Is there any way to check the goat-counter & giscus are working well?, It seems other requirements are fulfilled though.

Sadly, not. Those two APIs linked to demo site(`byanko55.github.io`), while the dev branch deploys the test page on `'byanko55.github.io/jekyll-theme-satellite'`. We can't change the deployment URL as we want.

**Comment by cvlian** [comment]
> > Is there any way to check the goat-counter & giscus are working well?, It seems other requirements are fulfilled though.
> 
> Sadly, not. Those two APIs linked to demo site(`byanko55.github.io`), while the dev branch deploys the test page on `'byanko55.github.io/jekyll-theme-satellite'`. We can't change the deployment URL as we want.
 
If so, register another URL to your account. I'm not sure but is that hard?

**Comment by byanko55** [comment]
> > > Is there any way to check the goat-counter & giscus are working well?, It seems other requirements are fulfilled though.
> > 
> > 
> > Sadly, not. Those two APIs linked to demo site(`byanko55.github.io`), while the dev branch deploys the test page on `'byanko55.github.io/jekyll-theme-satellite'`. We can't change the deployment URL as we want.
> 
> If so, register another URL to your account. I'm not sure but is that hard?

Not so hard I guess, but ONLY 1 domain can be registered per a single account. Could you do that instead of me? @mgarrixx  @cvlian

**Comment by byanko55** [comment]
Nah, you guys don't have to. I will do it on my another account.

**Review by cvlian — APPROVED** [review]
Marvelous thing you did.

**Review by mgarrixx — APPROVED** [review]
It's truly enough, Thanks!

**Pull request merged**
